---
title: "Plotting cross examples"
author: "Dr K"
date: "Year 2019"
output:
  html_document:
    df_print: paged
---

```{r include=FALSE,echo=FALSE}
require(tidyverse)
require(tigerstats)
data(ucdavis1)
davisdata <- na.omit(ucdavis1)

```

# Boxplots Cat ~ Numerical



```{r}
boxplot(dadheight~Sex,data=ucdavis1)
```
  
##Now with ggplot - first select the basic data

```{r}
basicCN <- ggplot(ucdavis1,aes(x=Sex,y=dadheight))
```
##Now add in boxplot

```{r}
basicCN + geom_boxplot()
```

  

# Barcharts Cat ~ Cat


```{r}
barchartGC(~Seat+Sex,data=ucdavis1)
```
```{r}
basicCC <- ggplot(davisdata,aes(x=Seat,fill=Sex))
basicCC + geom_bar()
basicCC + geom_bar(position=position_dodge())

```



##Scatterplots Numerical ~ Numerical  

```{r}
plot(Height~momheight,data=davisdata)
```

##Now we see why ggplot is so cool
```{r}
basicNN <- ggplot(davisdata,aes(x=Height,y=momheight))
```
##Now add scatterplot and fitted regression line + then add loess

```{r}
basicNN + geom_point() + geom_lm() + geom_smooth()
```



